package zuora

//ObjecName represents name of zuora object
type ObjecName string

//ObjectModel container struct for all Zuora objects
type ObjectModel struct {
	Account                                  ObjecName
	AccountingCode                           ObjecName
	AccountingPeriod                         ObjecName
	Amendment                                ObjecName
	BillingRun                               ObjecName
	Contact                                  ObjecName
	ContactSnapshot                          ObjecName
	CreditBalanceAdjustment                  ObjecName
	CreditMemo                               ObjecName
	CreditMemoApplication                    ObjecName
	CreditMemoApplicationItem                ObjecName
	CreditMemoItem                           ObjecName
	CreditMemoPart                           ObjecName
	CreditMemoPartItem                       ObjecName
	CreditTaxationItem                       ObjecName
	FXCustomRate                             ObjecName
	DebitMemo                                ObjecName
	DebitMemoItem                            ObjecName
	DebitTaxationItem                        ObjecName
	DiscountAppliedMetrics                   ObjecName
	Tenant                                   ObjecName
	PaymentGatewayReconciliationEventLog     ObjecName
	PaymentReconciliationJob                 ObjecName
	PaymentReconciliationLog                 ObjecName
	Invoice                                  ObjecName
	InvoiceAdjustment                        ObjecName
	InvoiceItem                              ObjecName
	InvoiceItemAdjustment                    ObjecName
	InvoicePayment                           ObjecName
	JournalEntry                             ObjecName
	JournalEntryItem                         ObjecName
	JournalRun                               ObjecName
	Order                                    ObjecName
	OrderAction                              ObjecName
	OrderElp                                 ObjecName
	OrderItem                                ObjecName
	OrderMrr                                 ObjecName
	OrderQuantity                            ObjecName
	OrderTcb                                 ObjecName
	OrderTcv                                 ObjecName
	Payment                                  ObjecName
	PaymentApplication                       ObjecName
	PaymentApplicationItem                   ObjecName
	PaymentMethod                            ObjecName
	PaymentMethodSnapshot                    ObjecName
	PaymentMethodTransactionLog              ObjecName
	UpdaterDetail                            ObjecName
	PaymentPart                              ObjecName
	PaymentPartItem                          ObjecName
	PaymentRun                               ObjecName
	PaymentTransactionLog                    ObjecName
	ProcessedUsage                           ObjecName
	Product                                  ObjecName
	ProductRatePlan                          ObjecName
	ProductRatePlanCharge                    ObjecName
	ProductRatePlanChargeTier                ObjecName
	RatePlan                                 ObjecName
	RatePlanCharge                           ObjecName
	RatePlanChargeTier                       ObjecName
	Refund                                   ObjecName
	RefundApplication                        ObjecName
	RefundApplicationItem                    ObjecName
	RefundInvoicePayment                     ObjecName
	RefundPart                               ObjecName
	RefundPartItem                           ObjecName
	RefundTransactionLog                     ObjecName
	RevenueChargeSummary                     ObjecName
	RevenueChargeSummaryItem                 ObjecName
	RevenueEvent                             ObjecName
	RevenueEventCreditMemoItem               ObjecName
	RevenueEventDebitMemoItem                ObjecName
	RevenueEventInvoiceItem                  ObjecName
	RevenueEventInvoiceItemAdjustment        ObjecName
	RevenueEventItem                         ObjecName
	RevenueEventItemCreditMemoItem           ObjecName
	RevenueEventItemDebitMemoItem            ObjecName
	RevenueEventItemInvoiceItem              ObjecName
	RevenueEventItemInvoiceItemAdjustment    ObjecName
	RevenueEventType                         ObjecName
	RevenueSchedule                          ObjecName
	RevenueScheduleCreditMemoItem            ObjecName
	RevenueScheduleDebitMemoItem             ObjecName
	RevenueScheduleInvoiceItem               ObjecName
	RevenueScheduleInvoiceItemAdjustment     ObjecName
	RevenueScheduleItem                      ObjecName
	RevenueScheduleItemCreditMemoItem        ObjecName
	RevenueScheduleItemDebitMemoItem         ObjecName
	RevenueScheduleItemInvoiceItem           ObjecName
	RevenueScheduleItemInvoiceItemAdjustment ObjecName
	Subscription                             ObjecName
	TaxableItemSnapshot                      ObjecName
	TaxationItem                             ObjecName
	UpdaterBatch                             ObjecName
	Usage                                    ObjecName
}

func newObjectModel() ObjectModel {
	return ObjectModel{
		Account:                                  "Account",
		AccountingCode:                           "AccountingCode",
		AccountingPeriod:                         "AccountingPeriod",
		Amendment:                                "Amendment",
		BillingRun:                               "BillingRun",
		Contact:                                  "Contact",
		ContactSnapshot:                          "ContactSnapshot",
		CreditBalanceAdjustment:                  "CreditBalanceAdjustment",
		CreditMemo:                               "CreditMemo",
		CreditMemoApplication:                    "CreditMemoApplication",
		CreditMemoApplicationItem:                "CreditMemoApplicationItem",
		CreditMemoItem:                           "CreditMemoItem",
		CreditMemoPart:                           "CreditMemoPart",
		CreditMemoPartItem:                       "CreditMemoPartItem",
		CreditTaxationItem:                       "CreditTaxationItem",
		FXCustomRate:                             "FXCustomRate",
		DebitMemo:                                "DebitMemo",
		DebitMemoItem:                            "DebitMemoItem",
		DebitTaxationItem:                        "DebitTaxationItem",
		DiscountAppliedMetrics:                   "DiscountAppliedMetrics",
		Tenant:                                   "Tenant",
		PaymentGatewayReconciliationEventLog:     "PaymentGatewayReconciliationEventLog",
		PaymentReconciliationJob:                 "PaymentReconciliationJob",
		PaymentReconciliationLog:                 "PaymentReconciliationLog",
		Invoice:                                  "Invoice",
		InvoiceAdjustment:                        "InvoiceAdjustment",
		InvoiceItem:                              "InvoiceItem",
		InvoiceItemAdjustment:                    "InvoiceItemAdjustment",
		InvoicePayment:                           "InvoicePayment",
		JournalEntry:                             "JournalEntry",
		JournalEntryItem:                         "JournalEntryItem",
		JournalRun:                               "JournalRun",
		Order:                                    "Order",
		OrderAction:                              "OrderAction",
		OrderElp:                                 "OrderElp",
		OrderItem:                                "OrderItem",
		OrderMrr:                                 "OrderMrr",
		OrderQuantity:                            "OrderQuantity",
		OrderTcb:                                 "OrderTcb",
		OrderTcv:                                 "OrderTcv",
		Payment:                                  "Payment",
		PaymentApplication:                       "PaymentApplication",
		PaymentApplicationItem:                   "PaymentApplicationItem",
		PaymentMethod:                            "PaymentMethod",
		PaymentMethodSnapshot:                    "PaymentMethodSnapshot",
		PaymentMethodTransactionLog:              "PaymentMethodTransactionLog",
		UpdaterDetail:                            "UpdaterDetail",
		PaymentPart:                              "PaymentPart",
		PaymentPartItem:                          "PaymentPartItem",
		PaymentRun:                               "PaymentRun",
		PaymentTransactionLog:                    "PaymentTransactionLog",
		ProcessedUsage:                           "ProcessedUsage",
		Product:                                  "Product",
		ProductRatePlan:                          "ProductRatePlan",
		ProductRatePlanCharge:                    "ProductRatePlanCharge",
		ProductRatePlanChargeTier:                "ProductRatePlanChargeTier",
		RatePlan:                                 "RatePlan",
		RatePlanCharge:                           "RatePlanCharge",
		RatePlanChargeTier:                       "RatePlanChargeTier",
		Refund:                                   "Refund",
		RefundApplication:                        "RefundApplication",
		RefundApplicationItem:                    "RefundApplicationItem",
		RefundInvoicePayment:                     "RefundInvoicePayment",
		RefundPart:                               "RefundPart",
		RefundPartItem:                           "RefundPartItem",
		RefundTransactionLog:                     "RefundTransactionLog",
		RevenueChargeSummary:                     "RevenueChargeSummary",
		RevenueChargeSummaryItem:                 "RevenueChargeSummaryItem",
		RevenueEvent:                             "RevenueEvent",
		RevenueEventCreditMemoItem:               "RevenueEventCreditMemoItem",
		RevenueEventDebitMemoItem:                "RevenueEventDebitMemoItem",
		RevenueEventInvoiceItem:                  "RevenueEventInvoiceItem",
		RevenueEventInvoiceItemAdjustment:        "RevenueEventInvoiceItemAdjustment",
		RevenueEventItem:                         "RevenueEventItem",
		RevenueEventItemCreditMemoItem:           "RevenueEventItemCreditMemoItem",
		RevenueEventItemDebitMemoItem:            "RevenueEventItemDebitMemoItem",
		RevenueEventItemInvoiceItem:              "RevenueEventItemInvoiceItem",
		RevenueEventItemInvoiceItemAdjustment:    "RevenueEventItemInvoiceItemAdjustment",
		RevenueEventType:                         "RevenueEventType",
		RevenueSchedule:                          "RevenueSchedule",
		RevenueScheduleCreditMemoItem:            "RevenueScheduleCreditMemoItem",
		RevenueScheduleDebitMemoItem:             "RevenueScheduleDebitMemoItem",
		RevenueScheduleInvoiceItem:               "RevenueScheduleInvoiceItem",
		RevenueScheduleInvoiceItemAdjustment:     "RevenueScheduleInvoiceItemAdjustment",
		RevenueScheduleItem:                      "RevenueScheduleItem",
		RevenueScheduleItemCreditMemoItem:        "RevenueScheduleItemCreditMemoItem",
		RevenueScheduleItemDebitMemoItem:         "RevenueScheduleItemDebitMemoItem",
		RevenueScheduleItemInvoiceItem:           "RevenueScheduleItemInvoiceItem",
		RevenueScheduleItemInvoiceItemAdjustment: "RevenueScheduleItemInvoiceItemAdjustment",
		Subscription:                             "Subscription",
		TaxableItemSnapshot:                      "TaxableItemSnapshot",
		TaxationItem:                             "TaxationItem",
		UpdaterBatch:                             "UpdaterBatch",
		Usage:                                    "Usage",
	}
}
